### ISSUE TITLE
"Error: invalid character ',' looking for beginning of object key string" when trying to browse a snapshot on a remote repo

### ISSUE THREAD

**Issue by BadJoKing** [ad-on-is/resticity#11]
When I click on the yellow path in the snapshot view, it tries to load something, but then fails with the message from the title.
The repo is set up on a sftp server running EndeavourOS (basically Arch).
I'm running resticity 1.0.46-1 (aur version) on CachyOS on the client side.
I followed [the repo initialization steps in the restic documentation](https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#sftp)
Here is a screenshot from the snapshot whose path I want to browse...
![Follow the yellow pathway or something...](https://github.com/user-attachments/assets/0258a5b9-689e-442a-bbb3-0f58de263690)
...and from it not working
![He no workey...](https://github.com/user-attachments/assets/14aedb74-e3fa-4873-be83-1fe1355df97f)
I really appreciate any information on how/whether this is fixable by me or if I just have to wait for some future update.
Thanks in advance.

EDIT: In the logs it gives me the following error message:
```
FetchError: [POST] "http://localhost:11278/api/repositories/58c1b1c0-2346-4835-a921-f43baa13b472/snapshots/e51958c9c2877a28da51bbcf7a852afe2cd9898585c0f3b98eb5d28f5885cebe/browse": 500 Internal Server Error
```

**Comment by QuarkZ26** [comment]
Getting the same error, on Arch

**Comment by ad-on-is** [comment]
Sorry for the delayed answer... I was on vacation.
I haven't worked on the project for a while now, so there haven't been any "breaking changes" ever since.

What version of restic are you using? Maybe they changed something there. All resticity does, is, it uses restic commands with the `--json` attribute and parses the json output.

Would you mind testing `restic -r /path/to/repo ls latest`

**Comment by QuarkZ26** [comment]
The above command indeed works and I can see the list of files that I have backed up.

I'm using Restic version 0.17.0-1, which was automatically installed as a dependency.

**Comment by QuarkZ26** [comment]
Ok, so I downloaded Restic 0.16.5 and it's working, so I'm guessing something changed in the 0.17 version that broke Resticity. They do have a long list of changes.

**Comment by BadJoKing** [comment]
Hi there,
I'm sorry for the late answer. I was on vacation without access to my laptop for a week.
I can confirm that downgrading the restic package to 0.16.5-1 solves the problem I've been having. 
I'll close this issue now.
Edit: Thanks for the help btw...

**Comment by QuarkZ26** [comment]
Shouldn't it be fixed with the latest version instead? With the amount of changes and bug fixes, it seems to be a better option than simply downgrading.

**Comment by ad-on-is** [comment]
@QuarkZ26 I totally agree here.

tbf, I mostly run It in a Docker and it serves my purpose without issues.

And, tbh... the current state of packaging on Linux, especially Flatpak (Flathub) in combination with electron-like-apps is a mess, which keeps me less motivated to work on it.

**Comment by NetworkJack2** [comment]
still getting this error on Arch. Can you fix for latest version please?
